# Generated by Django 5.0.7 on 2024-07-10 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=50, unique=True)),
                ('secret_key', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuentas.aplicaciones')),
            ],
        ),
    ]
