# Generated by Django 5.0.7 on 2024-07-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aplicaciones',
            new_name='Aplicacion',
        ),
    ]
