# Generated by Django 5.0.7 on 2024-07-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_rename_aplicaciones_aplicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='username',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
