# Generated by Django 5.0.7 on 2024-07-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_aplicacion_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacion',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
