# Generated by Django 5.0.7 on 2024-07-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_aplicacion_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicacion',
            name='password',
        ),
        migrations.RemoveField(
            model_name='aplicacion',
            name='username',
        ),
    ]
