# Generated by Django 5.0.7 on 2024-07-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0005_remove_aplicacion_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacion',
            name='api_key',
            field=models.CharField(default='i4QQF5yu6uwyO2gXTU4VmA', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='secret_key',
            field=models.CharField(default='3fx9Fg9iDqbLJnfjZQRc2A', max_length=50, unique=True),
        ),
    ]
