# Generated by Django 5.0.7 on 2024-07-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0006_alter_aplicacion_api_key_alter_aplicacion_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacion',
            name='api_key',
            field=models.CharField(default='EmNCjeAygo-fA95_ZsPHxA', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='aplicacion',
            name='secret_key',
            field=models.CharField(default='yvyihel5udQImFlOPFNQvw', max_length=50, unique=True),
        ),
    ]
